// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeNumbers.API.Data;

namespace PrimeNumbers.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190822043614_IntRes")]
    partial class IntRes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PrimeNumbers.API.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfEnd");

                    b.Property<DateTime>("DateOfStart");

                    b.Property<int>("MaxRangeData");

                    b.Property<int>("MinRangeData");

                    b.Property<string>("ResultValues");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
