// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeNumbers.API.Data;

namespace PrimeNumbers.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PrimeNumbers.API.Models.PrimeNumber", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ResultId");

                    b.HasKey("Number");

                    b.HasIndex("ResultId");

                    b.ToTable("PrimeNumber");
                });

            modelBuilder.Entity("PrimeNumbers.API.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfEnd");

                    b.Property<DateTime>("DateOfStart");

                    b.Property<int>("MaxRangeData");

                    b.Property<int>("MinRangeData");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("PrimeNumbers.API.Models.PrimeNumber", b =>
                {
                    b.HasOne("PrimeNumbers.API.Models.Result")
                        .WithMany("ResultsPrimeNumbers")
                        .HasForeignKey("ResultId");
                });
#pragma warning restore 612, 618
        }
    }
}
